{% set name = "d3rlpy" %}
{% set version = "2.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2d742d56f88a281992a45d778ff800026e4c7819c49c251e0786746420e69312

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - {{ pin_compatible('numpy') }}
    - pytorch >=2.5.0
    - tqdm
    - h5py
    - gym >=0.26.0
    - click
    - typing-extensions
    - structlog
    - colorama
    - dataclasses-json
    - gymnasium >=1.0.0

test:
  requires:
    - python {{ python_min }}
  imports:
    - d3rlpy
    - d3rlpy.dataset

about:
  home: https://github.com/takuseno/d3rlpy
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: An offline deep reinforcement learning library.

  description: |
    d3rlpy is a Python library providing the state-of-the-art data-driven deep
    reinforcement learning algorithms through scikit-learn style API.
  doc_url: https://d3rlpy.readthedocs.io
  dev_url: https://github.com/takuseno/d3rlpy

extra:
  recipe-maintainers:
    - takuseno
