{% set name = "d3rlpy" %}
{% set version = "0.70" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8b3d4da7bbdf72a8425d48e820cc48591afa02c1ab505be1b6369f86784729b3

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - numpy
    - Cython
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - pytorch
    - scikit-learn
    - tensorboardx
    - tqdm
    - gputil
    - h5py
    - gym
    - kornia
    - click
    - typing-extensions
    - structlog
    - colorama

test:
  imports:
    - d3rlpy
    - d3rlpy.dataset

about:
  home: https://github.com/takuseno/d3rlpy
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A data-driven deep reinforcement learning library as an out-of-the-box tool

  description: |
    d3rlpy is a Python library providing the state-of-the-art data-driven deep
    reinforcement learning algorithms through scikit-learn style API.
  doc_url: https://d3rlpy.readthedocs.io
  dev_url: https://github.com/takuseno/d3rlpy

extra:
  recipe-maintainers:
    - takuseno
