{% set name = "d3rlpy" %}
{% set version = "2.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 643c4ce11411d32730bf5f7a78e077106023eeea297d880742f75d8f7fae95a5

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - pytorch
    - tqdm
    - h5py
    - gym>=0.26.0
    - click
    - typing-extensions
    - structlog
    - colorama
    - dataclasses-json

test:
  imports:
    - d3rlpy
    - d3rlpy.dataset

about:
  home: https://github.com/takuseno/d3rlpy
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: An offline deep reinforcement learning library.

  description: |
    d3rlpy is a Python library providing the state-of-the-art data-driven deep
    reinforcement learning algorithms through scikit-learn style API.
  doc_url: https://d3rlpy.readthedocs.io
  dev_url: https://github.com/takuseno/d3rlpy

extra:
  recipe-maintainers:
    - takuseno
